services:
  ntg:
    build: .
    ports:
      - 8888:8888
    volumes:
      - .:/project
      - ../heightmaps:/heightmaps
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]